### ISSUE TITLE
Unnecessary Statement

### ISSUE THREAD

**Issue by DerekJxy** [dhillonks/cli-ssg#2]
For the code in __'bin/index.js'__,
__Line 50 - Line 57__
_if(argv.o != outputDir){
      if(fs.existsSync(argv.o)){
        if(!fs.lstatSync(argv.o).isDirectory()){
          throw new Error("Output path points to a file. Output directory must be valid")
        }
      }
      else throw new Error("Output directory must be valid");
    }_

This statement can be __deleted__ since the output path is _set by default._

**Comment by dhillonks** [comment]
These are actually needed to validate the output path entered by the user
https://github.com/dhillonks/cli-ssg/blob/2374ea98acef57eb7ed051b89c4e042a356bc782/bin/index.js#L48-L55
