### ISSUE TITLE
Code Improvement

### ISSUE THREAD

**Issue by DerekJxy** [dhillonks/cli-ssg#4]
For the __'generateHtml.js'__,
__Line 20__:      _if(!lines[1] && !lines[2]){_
Should be changed since you wanted to update your code in 

__Line 15__: _const lines = data.split(/\r?\n/);_
                 __TO__
_const lines = data.split(/\r?\n\r?\n/);_

The new code for the __Line 20__ could be something like this:
_if(lines[1] !== '' && !lines[2] !== ''){_

So that you can keep using the __same variable__ to get the __title__ of the article.

**Comment by dhillonks** [comment]
The existing delimiter in use `\r?\n` is already splitting the input line by line. I also don't see how these changes would improve the extraction of a file's title using the same variable.
